parameters:
    database_host: localhost
    database_username: root
    database_password: 123456
    database_name: warlikes
    facebook_app_id: '551213981665418'
    facebook_app_secret: 'd29941bb10e204f59506f39db86f2a07'
    facebook_app_host: 'http://dev.warlikes.com/'
    facebook_tab_url: 'http://www.google.com.ar'
    facebook_login_scope: 'basic_info, email, user_birthday, publish_actions'