parameters:
    database_host: localhost
    database_username: root
    database_password: 123456
    database_name: urb
    facebook_app_id: '738588072842792'
    facebook_app_secret: '2b81995191260128c93214818cbf8050'
    facebook_app_host: 'http://dev.urb.com/'
    facebook_tab_url: 'http://www.google.com.ar'
    facebook_login_scope: 'basic_info, email, user_birthday, publish_actions, user_photos'